name: Animal Farm Node.js CI

on:
  push:
   branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: echo "hello world"
